# Generated by Django 3.2.9 on 2021-11-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('fnc', models.CharField(max_length=100)),
                ('image', models.ImageField(default='static/img/logo/rdc image.jpg', upload_to='static/profile_pics/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
