# Generated by Django 3.2.9 on 2021-11-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personnel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='img_url',
            field=models.CharField(default='img/logo/lef.png', max_length=100, verbose_name='img/logo/lef.png'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(default='img/logo/lef.png', upload_to='static/profile_pics/'),
        ),
    ]
