# Generated by Django 3.2.9 on 2021-11-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20211126_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='img_url',
            new_name='img',
        ),
    ]
