# Generated by Django 3.2.9 on 2021-11-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_rename_img_url_personnel_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='img',
            new_name='imgpath',
        ),
    ]
