# Generated by Django 3.2.9 on 2021-11-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_rename_img_personnel_imgpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='image',
        ),
    ]
