# Generated by Django 3.2.9 on 2021-11-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_remove_personnel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='image',
            field=models.ImageField(default='img/logo/lef.png', upload_to='static/img/personnel/'),
        ),
    ]
