# Generated by Django 3.2.9 on 2021-11-26 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_personnel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='image',
        ),
    ]
