# Generated by Django 3.2.9 on 2021-11-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_remove_personnel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={},
        ),
    ]
