# Generated by Django 3.2.9 on 2021-11-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_alter_personnel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['id']},
        ),
    ]
