# Generated by Django 3.2.9 on 2021-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_personnel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(default='static/img/logo/rdc image.jpg', upload_to='static/profile_pics/'),
        ),
    ]
