# Generated by Django 3.2.9 on 2021-11-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_personnel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
