# Generated by Django 3.2.9 on 2021-11-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_rename_slides_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['id']},
        ),
    ]
