# Generated by Django 3.2.9 on 2021-11-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_auto_20211129_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='imgpath',
            field=models.CharField(max_length=100),
        ),
    ]
